### ISSUE TITLE
Type error.

### ISSUE THREAD

**Issue by UG40A** [dan0102dan/export_vk_chat#2]
Hi! Thanks for your work, but it doesn't work for me. I getting an error:

```
/.../.../export_vk_chat/functions/getChatMessages.ts:39
}
                                                                       ^
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at __values (/.../.../export_vk_chat/functions/getChatMessages.ts:39:72)
    at /.../.../export_vk_chat/functions/getChatMessages.ts:21:25
    at step (/.../.../export_vk_chat/functions/getChatMessages.ts:33:23)
    at Object.next (/.../.../export_vk_chat/functions/getChatMessages.ts:14:53)
    at fulfilled (/.../...//functions/getChatMessages.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
  
```

**Comment by dan0102dan** [comment]
Hi there!

Thank you for reporting this issue. I appreciate your patience. I have just released an update that should address the problem you encountered.

Please update to the latest version and let me know if you experience any further issues. If the problem persists, feel free to reach out again.
